### ISSUE TITLE
UDP protocol has been dropped in Sentry 7

### ISSUE THREAD

**Issue by crankycoder** [mozilla-services/heka-mozsvc-plugins#22]
Sentry 7 has dropped official support for UDP.  

The sentry output should be updated to support a separate goroutine that pushes HTTP requests into Sentry.

Sentry changelog : http://sentry.readthedocs.org/en/latest/changelog/#version-7-0-0

**Comment by azylman** [comment]
:+1: This would be awesome.

I just set up Heka specifically for Sentry, didn't realize it didn't support the newest Sentry. :(

**Comment by azylman** [comment]
I think I'm going to work on this tomorrow and use the [official Sentry go client](https://github.com/getsentry/raven-go).

Do you guys want a separate goroutine for each message to send to Sentry? Or something like a channel of messages to send to Sentry that N goroutines are reading from?

**Comment by crankycoder** [comment]
Awesome!  

I think that I'd rather see a channel of messages rather than spinning up a goroutine per message.  cc: @rafrombrc

**Comment by rafrombrc** [comment]
Yes, definitely not a goroutine per message. I'd say it should either send messages synchronously, or, at most, have one goroutine accepting messages from the output's InChan and a separate goroutine sending them off to Sentry.

**Comment by azylman** [comment]
I'll probably do synchronous, then, since that's easier - I was just thinking goroutine because the original issue suggested one

**Comment by rafrombrc** [comment]
+1. Start simple.
